### PR TITLE
I translated to spanish, I hope you find it useful!

### PR DESCRIPTION
**Pull request by AndresCidoncha**

### CODE REVIEW

**Comment by vasilisvg** [comment]
This is fantastic! Thank you so much. There is a small issue though: it looks like you worked on a slightly older version of the code base. If I understand [this graph](https://github.com/vasilisvg/human-colours/network) correctly, the last few commits are missing from your code.

**Comment by AndresCidoncha** [comment]
Ups! Sorry! Now it's ok I hope!

**Comment by vasilisvg** [comment]
Do you think you can [rebase your pull request on top of master](https://stackoverflow.com/questions/17182624/contributing-to-project-on-github-how-to-rebase-my-pull-request-on-top-of-mast)? There's an explanation in [that link](https://stackoverflow.com/questions/17182624/contributing-to-project-on-github-how-to-rebase-my-pull-request-on-top-of-mast). That would really help me out. I'm a bit of a n00b when it comes to git conflicts, to be honest, and I can't find out how to fix this myself.

**Comment by AndresCidoncha** [comment]
I can't fix it, even with the link, but I have another idea, I will fork your repo, add my changes and request the pull for that fork

**Pull request closed without merging**
